- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  packages:
    - font-manager-git
    - galculator
    - flameshot
    - plank
    - arcolinux-plank-themes-git
    - screenkey-git
    - arcolinux-variety-git
    - variety
    - xfburn
- name: "Communication"
  description: "Communication"
  critical: false
  hidden: false
  selected: false
  packages:
    - discord
    - qtox
    - riot-desktop
    - skypeforlinux-stable-bin
    - teams
    - telegram-desktop
    - viber
    - wire-desktop
    - zoom
- name: "Conky"
  description: "Conky and conky collection"
  critical: false
  hidden: false
  selected: false
  packages:
    - conky-lua-archers
    - arcolinux-conky-collection-git
    - yad
    - arcolinux-pipemenus-git
- name: "File Manager"
  description: "Filemanager"
  critical: false
  hidden: false
  selected: false
  packages:
    - caja
    - dolphin
    - mc
    - nautilus
    - nemo
    - nemo-fileroller
    - pcmanfm
    - ranger
    - thunar
    - thunar-archive-plugin
- name: "Fonts"
  description: "Fonts"
  critical: false
  hidden: false
  selected: false
  packages:
    - adobe-source-sans-pro-fonts
    - awesome-terminal-fonts
    - terminus-font
    - ttf-bitstream-vera
    - ttf-droid
    - ttf-fira-code
    - ttf-font-awesome
    - ttf-hack
    - ttf-inconsolata
    - ttf-liberation
    - ttf-roboto
    - ttf-ubuntu-font-family
- name: "Games"
  description: "Games"
  critical: false
  hidden: false
  selected: false
  packages:
    - arcolinux-meta-steam
    - lutris
    - minecraft-launcher
- name: "Git"
  description: "Git"
  critical: false
  hidden: false
  selected: false
  packages:
    - gitahead-bin
    - gitfiend
    - gitkraken
- name: "Graphics"
  description: "Graphics"
  critical: false
  hidden: false
  selected: false
  packages:
    - blender
    - darktable
    - digikam
    - gimp
    - gpick
    - inkscape
    - krita
    - nitrogen
    - nomacs
    - pinta
    - ristretto
- name: "Fun"
  description: "Fun"
  critical: false
  hidden: false
  selected: false
  packages:
    - arcolinux-meta-fun
- name: "Internet"
  description: "Internet"
  critical: false
  hidden: false
  selected: false
  packages:
    - brave
    - chromium
    - deluge
    - dropbox
    - evolution
    - falkon
    - filezilla
    - firefox
    - firefox-adblock-plus
    - firefox-i18n-$LOCALE
    - geary
    - google-chrome
    - hexchat
    - insync
    - ktorrent
    - opera
    - pidgin
    - qbittorrent
    - thunderbird
    - transmission-gtk
    - vivaldi
    - whatsapp-nativefier
- name: "Multimedia"
  description: "Multimedia"
  critical: false
  hidden: false
  selected: false
  packages:
    - ardour
    - audacious
    - audacity
    - celluloid
    - clementine
    - deadbeef
    - elisa
    - guvcview
    - handbrake
    - kdenlive
    - lollypop
    - lmms
    - obs-studio
    - openshot
    - mpv
    - peek
    - pragha
    - rhythmbox
    - simplescreenrecorder
    - soundconverter
    - smplayer
    - spotify
    - spotifywm-git
    - vlc
- name: "Password Manager"
  description: "Password manager"
  critical: false
  hidden: false
  selected: false
  packages:
    - bitwarden-bin
    - enpass-bin
    - keepassxc
    - lastpass
- name: "Privacy"
  description: "Applications that ensure your privacy"
  critical: false
  hidden: false
  selected: false
  packages:
    - tor-browser
    - tor
    - privoxy
- name: "Terminals"
  description: "Terminals"
  critical: false
  hidden: false
  selected: false
  packages:
    - alacritty
    - gnome-terminal
    - guake
    - kitty
    - konsole
    - lxterminal
    - sakura
    - terminator
    - termite
    - tilix
    - tilda
    - tmux
- name: "Theming"
  description: "Theming"
  critical: false
  hidden: false
  selected: false
  packages:
    - adapta-gtk-theme
    - arc-icon-theme
    - arcolinux-arc-kde
    - arcolinux-arc-themes-nico-git
    - breeze
    - faba-icon-theme
    - gnome-icon-theme
    - moka-icon-theme
    - numix-circle-arc-icons-git
    - numix-circle-icon-theme-git
    - numix-gtk-theme-git
    - openbox-themes-pambudi-git
    - oxy-neon
    - paper-icon-theme
    - papirus-icon-theme
    - surfn-arc-breeze-icons-git
    - xcursor-breeze
    - xcursor-simpleandsoft
- name: "Usb"
  description: "Usb"
  critical: false
  hidden: false
  selected: false
  packages:
    - etcher-bin
    - imagewriter
    - mintstick-git
    - woeusb
- name: "Virtualbox for Linux kernel"
  description: "Installs virtualbox for linux kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-headers
- name: "Virtualbox for Linux-lts kernel"
  description: "Installs virtualbox for linux-lts kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-lts-headers
    - linux-lts
- name: "Zsh"
  description: "Zsh"
  critical: false
  hidden: false
  selected: false
  packages:
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
    - oh-my-zsh-git
    - arcolinux-zsh-git
