- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  packages:
    - font-manager-git
    - galculator
    - flameshot
    - plank
    - arcolinux-plank-themes-git
    - screenkey-git
    - arcolinux-variety-git
    - variety
    - xfburn
- name: "Calligra"
  description: "Office Suite"
  critical: false
  hidden: false
  selected: false
  packages:
    - calligra
    - calligra-plan
- name: "Conky"
  description: "Conky and conky collection"
  critical: false
  hidden: false
  selected: false
  packages:
    - conky-lua-archers
    - arcolinux-conky-collection-git
    - yad
    - arcolinux-pipemenus-git
- name: "Development"
  description: "Development"
  critical: false
  hidden: false
  selected: false
  packages:
    - atom
    - code
    - geany
    - geany-plugins
    - kdevelop
    - sublime-text-dev
- name: "File Manager"
  description: "Filemanager"
  critical: false
  hidden: false
  selected: false
  packages:
    - caja
    - dolphin
    - mc
    - nautilus
    - nemo
    - nemo-fileroller
    - pcmanfm
    - ranger
    - thunar
    - thunar-archive-plugin
- name: "Fonts"
  description: "Fonts"
  critical: false
  hidden: false
  selected: false
  packages:
    - adobe-source-sans-pro-fonts
    - awesome-terminal-fonts
    - terminus-font
    - ttf-bitstream-vera
    - ttf-droid
    - ttf-fira-code
    - ttf-font-awesome
    - ttf-hack
    - ttf-inconsolata
    - ttf-liberation
    - ttf-roboto
    - ttf-ubuntu-font-family
- name: "Games"
  description: "Games"
  critical: false
  hidden: false
  selected: false
  packages:
    - arcolinux-meta-steam
    - lutris
- name: "Graphics"
  description: "Graphics"
  critical: false
  hidden: false
  selected: false
  packages:
    - blender
    - darktable
    - digikam
    - gimp
    - gpick
    - inkscape
    - krita
    - nitrogen
    - nomacs
    - pinta
    - ristretto
- name: "Fun"
  description: "Fun"
  critical: false
  hidden: false
  selected: false
  packages:
    - arcolinux-meta-fun
- name: "Internet"
  description: "Internet"
  critical: false
  hidden: false
  selected: false
  packages:
    - brave
    - chromium
    - deluge
    - discord
    - dropbox
    - evolution
    - falkon
    - filezilla
    - firefox
    - firefox-i18n-$LOCALE
    - geary
    - hexchat
    - insync
    - ktorrent
    - opera
    - pidgin
    - qbittorrent
    - telegram-desktop
    - thunderbird
    - transmission-gtk
    - vivaldi
- name: "Libre Office Fresh"
  description: "Installs libre office fresh - feature branch - conflicts with still"
  critical: false
  hidden: false
  selected: false
  packages:
    - libreoffice-fresh
    - libreoffice-fresh-$LOCALE
    - hunspell-$LOCALE
- name: "Libre Office Still"
  description: "Installs libre office still - stable branch - conflicts with fresh"
  critical: false
  hidden: false
  selected: false
  packages:
    - libreoffice-still
    - libreoffice-still-$LOCALE
    - hunspell-$LOCALE
- name: "Multimedia"
  description: "Multimedia"
  critical: false
  hidden: false
  selected: false
  packages:
    - ardour
    - audacious
    - audacity
    - celluloid
    - clementine
    - deadbeef
    - elisa
    - guvcview
    - handbrake
    - kdenlive
    - lollypop
    - lmms
    - obs-studio
    - openshot
    - mpv
    - peek
    - pragha
    - rhythmbox
    - simplescreenrecorder
    - soundconverter
    - smplayer
    - spotify
    - spotifywm-git
    - vlc
- name: "Privacy"
  description: "Applications that ensure your privacy"
  critical: false
  hidden: false
  selected: false
  packages:
    - tor-browser
    - tor
    - privoxy
- name: "Themes"
  description: "Themes"
  critical: false
  hidden: false
  selected: false
  packages:
    - adapta-gtk-theme
    - arc-icon-theme
    - arcolinux-arc-kde
    - arcolinux-arc-themes-nico-git
    - breeze
    - faba-icon-theme
    - gnome-icon-theme
    - moka-icon-theme
    - numix-circle-arc-icons-git
    - numix-circle-icon-theme-git
    - numix-gtk-theme-git
    - openbox-themes-pambudi-git
    - oxy-neon
    - paper-icon-theme
    - papirus-icon-theme
    - surfn-arc-breeze-icons-git
    - xcursor-breeze
    - xcursor-simpleandsoft
- name: "Utilities"
  description: "Utilities"
  critical: false
  hidden: false
  selected: false
  packages:
    - baobab
    - catfish
    - etcher-bin
    - evince
    - gitahead-bin
    - gitfiend
    - glances
    - glxinfo
    - grsync
    - gtop
    - gufw
    - hddtemp
    - imagewriter
    - lm_sensors
    - open-vm-tools
    - meld
    - mintstick-git
    - pamac-aur
    - powertop
    - simple-scan
    - systemd-manager
    - timeshift
    - vnstat
    - wttr
    - youtube-dl
- name: "Virtualbox for Linux kernel"
  description: "Installs virtualbox for linux kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-headers
- name: "Virtualbox for Linux-lts kernel"
  description: "Installs virtualbox for linux-lts kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-lts-headers
    - linux-lts
- name: "WPS Office"
  description: "Installs wps office"
  critical: false
  hidden: false
  selected: false
  packages:
    - wps-office
    - wps-office-mime
    - ttf-wps-fonts
