- name: "ArcoLinux Dev"
  description: "Development software"
  critical: false
  hidden: false
  selected: false
  packages:
    - firefox
    - sublime-text-dev
    - flameshot
    - scrot
    - meld
    - the_platinum_searcher-bin
    - thunar
    - thunar-archive-plugin
    - arcolinux-xfce-git
    - telegram-desktop
    - discord
